### ISSUE TITLE
RHEL9 - Unable to load lvm attributes [lvs.yaml] for version [2.03.16(2)].

### ISSUE THREAD

**Issue by cmcconkey** [sous-chefs/lvm#226]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

Getting this error all RHEL 9 lvm2 version 9:2.03.16-3.el9 
Unable to load lvm attributes [lvs.yaml] for version [2.03.16(2)].

## :pancakes: Cookbook version  

lvm (6.1.2)

## :woman_cook:  Chef-Infra Version

Chef Infra Client, version 17.9.46

## :tophat: Platform details

Operating system distribution and release version. Cloud provider if running in the cloud.

Red Hat Enterprise Linux release 9.1 (Plow)   Azure

## Steps To Reproduce

  * lvm_physical_volume[/dev/sdc] action create[2022-11-22T11:26:48-06:00] INFO: Processing lvm_physical_volume[/dev/sdc] action create (hrb_rh_appdata_cb::add_appdata line 24)

    ================================================================================
    Error executing action `create` on resource 'lvm_physical_volume[/dev/sdc]'
    ================================================================================

    ArgumentError
    -------------
    Unable to load lvm attributes [lvs.yaml] for version [2.03.16(2)]. The version/object may not be supported or you may need to upgrade the chef-ruby-lvm-attrib gem. Error [No such file or directory @ rb_sysopen - /opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-ruby-lvm-attrib-0.3.11/lib/lvm/attributes/2.03.16(2)/lvs.yaml]

## :police_car: Expected behavior

create an lvm 

## :heavy_plus_sign: Additional context

If we downgrade lvm2 version to 9:2.03.14-4.el9 it works.
upgrade to lvm2 latest version ( 9:2.03.16-3.el9 ) it fails

**Comment by ianl678** [comment]
Logged this against the LVM GEM: https://github.com/sous-chefs/chef-ruby-lvm-attrib/issues/44
